# Generated by Django 5.0.3 on 2024-04-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='News_Feed',
            fields=[
                ('Feed_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreNewsNexus.admin_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feed_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreNewsNexus.news_feed')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreNewsNexus.user_registration')),
            ],
        ),
    ]
